name: object_cxr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  #  - pillow-simd

  - cudatoolkit=10.1
  - pytorch=1.5
  - torchvision=0.6

  - opencv
  - cython
  - scipy
  - scikit-learn
  #  - matplotlib
  - tqdm
  - pandas
  - pyyaml
  - scikit-image
  - shapely
  - pip
  - pip:
      - tensorboardX
      - pillow-simd
      - future
      - mlflow
      - pymysql
#    - lazy-import
      - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
      - git+https://github.com/NVIDIA/apex.git@1f2aa9156547377a023932a1512752c392d9bbdf
#    - torchsummary
      - pretrainedmodels
      - efficientnet-pytorch
#    - git+https://github.com/facebookresearch/detectron2.git@v0.1.1
#    - detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
      - https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/detectron2-0.1.3%2Bcu101-cp37-cp37m-linux_x86_64.whl
#    - git+https://github.com/open-mmlab/mmdetection.git

